### PR TITLE
Some improvement

### PR DESCRIPTION
**Pull request by skyline75489**
- refactor into many files
- support python2
- more pythonic

### CODE REVIEW

**Comment by udaysagar2177** [comment]
@skyline75489 Sorry for the late reply. I want to point out one thing. 
The refactored algorithm and the original algorithm does not produce same output.
For example, with key as "awdrgyji" and message as "I am awesome"
Output of refactored algorithm is 5cdc890c4e3e34ad61c43b8a1651b157
Output of original algorithm is 532864427e0445894383e8ecf83bcc06
Can you look into it?

**Comment by skyline75489** [comment]
I'm testing this program on my computer using your example. The results seems to be OK.

**Comment by udaysagar2177** [comment]
Sorry, my bad! Your algorithm is good with python 3. 
**New Issue:** I was using python 2.7 to run the program in the last comment. You are saying that you have added python 2 support but surprisingly, your algorithm is not producing the same output with python 2.7 and original algorithm is working fine with python 2.7

Your algorithm with 2.7
screen shot 2015-10-07 at 8 43 14 pm

My algorithm with 2.7
screen shot 2015-10-07 at 8 46 18 pm

**Comment by skyline75489** [comment]
This is because the input is surrounded with double quotes. You are using `"awdrgyji"` and I'm using `awdrgyji` (no double quotes). The double quotes make no difference in Python3 when using `input()`. However with Python2 I'm using `raw_input` instead of `input()` like in your old program, hence the different results.

**Comment by udaysagar2177** [comment]
Oh okay! sorry for mis-understanding. I will merge it in a day or two.

**Pull request merged**
